### ISSUE TITLE
https请求CORS错误

### ISSUE THREAD

**Issue by Dragon-Tab** [lijiejie/swagger-exp#20]
大佬 不是禁用cors了吗 这种情况该怎么解决
![image](https://github.com/user-attachments/assets/0073ad9f-e99b-4889-a228-6b6feb520322)

**Comment by lijiejie** [comment]
你可能需要F12 看看控制台是否有什么提示？  另外直接访问接口是成功的么？

**Comment by Dragon-Tab** [comment]
![image](https://github.com/user-attachments/assets/a0207e09-dc62-4e21-b5e1-b7e9f8bae7d1)
![image](https://github.com/user-attachments/assets/0208e00f-5ac0-421c-bb25-dfa4253dd61e)

**Comment by Dragon-Tab** [comment]
大佬 不好意思 解决了 是因为浏览器代理插件忘记关了
