### ISSUE TITLE
ModuleNotFoundError: No module named 'urlparse'

### ISSUE THREAD

**Issue by suiyideali1997** [lijiejie/swagger-exp#4]
Traceback (most recent call last):
  File "/root/mytools/swagger-exp/./swagger-exp.py", line 10, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by Mr-xn** [comment]
> Traceback (most recent call last):
> File "/root/mytools/swagger-exp/./swagger-exp.py", line 10, in
> import urlparse
> ModuleNotFoundError: No module named 'urlparse'

可以试试 python2 因为 urlparse 在 python2中默认可以 
但是我测试的时候 也有个编码问题 python2的编码问题太多了 看作者修不修吧 或者自己修改支持python3

**Comment by lijiejie** [comment]
感谢反馈，可以先试试pytnon2 执行，稍后我看看增加几行代码，支持python3

**Comment by DevilMayCrying** [comment]
swagger-exp/lib/common.py", line 3, in <module>
    import _winreg
ImportError: No module named _winreg

python2执行报这个错误

**Comment by shuaiZend** [comment]
> 感谢反馈，可以先试试pytnon2 执行，稍后我看看增加几行代码，支持python3

姐姐什么时候更新啊，python3等着用呢

**Comment by lijiejie** [comment]
已经增加了Python3 支持
